imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}

replicaCount: 1

# Image configuration
image:
  repository: lucshelton/link-extractor
  tag: "python-latest-linux-amd64"
  pullPolicy: IfNotPresent

# Pod-specific labels
labels:
  app.kubernetes.io/name: link-extractor
  app.kubernetes.io/component: worker
  app.kubernetes.io/part-of: web-crawling-suite
  app.kubernetes.io/managed-by: Helm

# Pod-specific annotations
annotations:
  description: "A Pod that runs the link-extractor application"
  maintainer: "lucshelton@gmail.com"

# Resources configuration
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Command and arguments for the container
args: ["-u", "https://news.bbc.co.uk/", "-o", "json"]
command: []

# Security context for the container
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

# Pod security context
podSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
