server:
  persistentVolume:
    enabled: true
    size: 20Gi
  service:
    type: NodePort
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
