apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.fullnameOverride | default .Release.Name }}
  labels:
    {{- include "link-extractor.labels" . | nindent 4 }}
  annotations:
    {{- include "link-extractor.annotations" . | nindent 4 }}
spec:
  imagePullSecrets:
    {{- if .Values.imagePullSecrets }}
    {{- toYaml .Values.imagePullSecrets | nindent 2 }}
    {{- end }}
  containers:
    - name: link-extractor
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      args: {{ .Values.args | toJson }}
      resources:
        limits:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
        requests:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
      lifecycle:
        postStart:
          exec:
            command: {{ .Values.args | toJson }}
  {{- if .Values.podSecurityContext }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 2 }}
  {{- end }}
  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 2 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 2 }}
  {{- end }}
  {{- if .Values.affinity }}
  affinity:
    {{- toYaml .Values.affinity | nindent 2 }}
  {{- end }}
  restartPolicy: Never
