apiVersion: v1
kind: Service
metadata:
  name: {{ include "link-extractor-app-job.fullname" . }}
  labels:
    {{- include "link-extractor-app-job.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "link-extractor-app-job.selectorLabels" . | nindent 4 }}
