repositories:
  - name: aqua
    url: https://aquasecurity.github.io/helm-charts/
  - name: falco
    url: https://falcosecurity.github.io/charts
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  - name: link-extractor-app-pod
    namespace: link-extractor
    chart: ./../../../Helm/Charts/link-extractor-app-pod
    values:
      - ./../../../Helm/Values/Python/values.yaml

  # Kubernetes Dashboard
  - name: kubernetes-dashboard
    namespace: kube-system
    chart: kubernetes-dashboard/kubernetes-dashboard
    # version: 5.11.1 # Replace with the desired version
    values:
      - ./values_dashboard.yaml # Optional: Add custom values for the dashboard


  # - name: falco
  #   namespace: security
  #   chart: falco/falco
  #   version: 1.5.0 # Optional: Specify a specific version of the chart
  #   values:
  #     - ./path/to/falco-values.yaml # Replace with your custom values file

  # - name: trivy
  #   namespace: security
  #   chart: aqua/trivy
  #   version: 2.0.0 # Replace with the desired version of Trivy
  #   values:
  #     - ./path/to/trivy-values.yaml # Replace with your custom values file for Trivy
