[tool.poetry]
name = "link-extractor"
version = "0.1.6"
description = ""
authors = ["Luc Shelton <lucshelton@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/loveduckie/sre-devops-case-study"
repository = "https://github.com/loveduckie/sre-devops-case-study"
documentation = "https://github.com/loveduckie/sre-devops-case-study/-/wikis/home"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [
    { include = "link_extractor/**/*" },
    { include = "link_extractor_tests/**/*" }
]
[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.11.7"
beautifulsoup4 = "^4.12.3"
click = "^8.1.7"
rich = "^13.9.4"
rich-click = "^1.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
link-extractor = 'link_extractor.__main__:main'

[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.group.docs.dependencies]
sphinx = "^7.4.4"
sphinx-rtd-theme = "^2.0.0"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pylint = "^3.2.5"


[tool.poetry.group.test.dependencies]
coverage = "^7.6.0"

[tool.poetry_bumpversion.file."link_extractor/__init__.py"]
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'