name: "Build Docker: .NET"

on:
  push:
    paths:
      - "Solutions/DotNet/LinkExtractor/**"
  pull_request:
    paths:
      - "Solutions/DotNet/LinkExtractor/**"
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-dotnet:
    uses: ./.github/workflows/shared/docker/build_docker.yml
    with:
      dockerfile: ./Solutions/DotNet/LinkExtractor/LinkExtractor/Dockerfile
      context: ./Solutions/DotNet/LinkExtractor
      image: link-extractor-dotnet:latest
      cache_image: link-extractor-dotnet:cache
      platforms: ${{ github.event.inputs.platforms }}
    # secrets:
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
