name: "Build Docker: Python"

on:
  push:
    paths:
      - "Solutions/Python/link-extractor/**"
  pull_request:
    paths:
      - "Solutions/Python/link-extractor/**"
  workflow_dispatch:
    inputs:
      platforms:
        description: "Comma-separated list of target platforms"
        required: false
        type: string
        default: "linux/amd64,linux/arm64,linux/arm64/v8"
      build_args:
        description: "Comma-separated list of build arguments (key=value)"
        required: false
        type: string
        default: ""

jobs:
  setup-build-vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BUILD_DATE=\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"" >> $GITHUB_ENV
          echo "BUILD_UID=\"$(uuidgen)\"" >> $GITHUB_ENV

  build-docker-python:
    name: "Build Docker Image (Python)"
    uses: ./.github/workflows/build_docker.yml
    with:
      dockerfile: ./Solutions/Python/link-extractor/Dockerfile
      context: ./Solutions/Python/link-extractor
      image: python
      cache_image: link-extractor-python:cache
      platforms: ${{ github.event.inputs.platforms }}
      build_args: ${{ github.event.inputs.build_args }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
