name: "Build Docker: .NET"

on:
  push:
    paths:
      - "Solutions/DotNet/LinkExtractor/**"
  pull_request:
    paths:
      - "Solutions/DotNet/LinkExtractor/**"
  workflow_dispatch:
    inputs:
      platforms:
        description: "Comma-separated list of target platforms"
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      build_args:
        description: "Comma-separated list of build arguments (key=value)"
        required: false
        type: string
        default: ""

jobs:
  build-docker-dotnet:
    uses: ./.github/workflows/build_docker.yml
    with:
      dockerfile: ./Solutions/DotNet/LinkExtractor/LinkExtractor/Dockerfile
      context: ./Solutions/DotNet/LinkExtractor
      image: dotnet
      cache_image: link-extractor-dotnet:cache
      platforms: ${{ github.event.inputs.platforms }}
      build_args: ${{ github.event.inputs.build_args }}
    # secrets:
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
