name: "Build, Test, and Package: Python"

on:
  push:
    paths:
      - "Solutions/Python/link-extractor/**"
  pull_request:
    paths:
      - "Solutions/Python/link-extractor/**"
  workflow_dispatch:
    inputs:
      bump_version:
        description: "Bump version (manual trigger)"
        required: false
        default: false
        type: boolean

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Specify the Python version

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install Dependencies with Poetry
      - name: Install Dependencies
        run: |
          cd Solutions/Python/link-extractor
          poetry install

      # Run Tests
      # - name: Run Tests
      #   run: |
      #     cd Solutions/Python/link-extractor
      #     poetry run pytest
      - name: Run Tests
        run: |
          cd Solutions/Python/link-extractor
          poetry run coverage run --source=. -m unittest discover -s .

      # Build the Package
      - name: Build Package
        run: |
          cd Solutions/Python/link-extractor
          poetry build

      # Upload the package artifact
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: link-extractor-package
          path: Solutions/Python/link-extractor/dist/

  bump-version:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.bump_version == 'true' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install Dependencies with Poetry
      - name: Install Dependencies
        run: |
          cd Solutions/Python/link-extractor
          poetry install

      # Bump Version
      - name: Bump Version
        run: |
          cd Solutions/Python/link-extractor
          poetry version patch
